config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'users/new'
  get 'static_pages/about'
  get 'static_pages/home'
  get  '/help',    to: 'static_pages#help'
  get '/blog' , to: 'static_pages#blogs'
  # get 'static_pages/help'
 
  resources :users do
     resources :microposts
  end
  
  get  '/signup',  to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "users#index"  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


   has_secure_password
   
   validates :password, presence: true, length: { minimum: 6 }
   
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action  :set_user, only: [:show, :edit, :update, :destroy]
  before_action  :logged_in_user, :correct_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
    # @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @microposts = @user.microposts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
         flash[:success] = "Profile updated"
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_form.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(user) do |f| %>
    
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name , class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password , class: "form-control"%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation , class: "form-control"%>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
        <br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
    <br>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

<br>
<hr/>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="row">
        <td> <%= gravatar_for user %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <%= will_paginate %>


</table>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<p id="notice"><%= notice %></p>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid">
  
  <div class="row">
    <div class="col-md-4">
      <section class="user_info">
        <div>
          <%= gravatar_for @user %>
        </div>
        <div>
          <h3>
            <%= @user.name %>
            <br>
            <%= @user.email %>
          </h3>
        </div>
      </section>
      
        <div>
          <p style="overflow:hidden">
            <%= @user.password_digest %>
          </p>
        </div>
        
        <div class="container-fluid" style="border: 2px solid grey">
          
          <%= link_to "New Post", new_user_micropost_path(@user), class: "btn btn-primary" %>

        </div>
  
    </div>
    <div class="col-md-4">
      <h1>Microposts</h1>
    
      <table class="table">
        <thead>
            <th>Content</th>
            <th>User</th>
            <th>Posted</th>
        </thead>
      
        <tbody>
          <% @microposts.each do |micropost| %>
            <tr class="row">
              <td><%= micropost.content %></td>
              <td><%= micropost.user_id %></td>
              <td> <%= time_ago_in_words(micropost.created_at) %> ago.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
    </div>
    
    
    
  </div>
  
  
  <div class="container">
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
  </div>

</div>