config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'users/new'
  get 'static_pages/about'
  get 'static_pages/home'
  get  '/help',    to: 'static_pages#help'
  get '/blog' , to: 'static_pages#blogs'
  # get 'static_pages/help'
 
  resources :users do
     resources :microposts
  end
  
  get  '/signup',  to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "users#index"  
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :content, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost
  
  # before_action :set_micropost, only: [:new, :show, :edit, :update, :destroy, :create]

  # GET /microposts
  # GET /microposts.json
  def index
    
    @microposts = @user.microposts.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = @user.microposts.build()
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    
    @micropost = @user.microposts.create(micropost_params)
    puts @micropost
    puts "Created micropost"
    
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to user_microposts_path, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @user = User.find(params[:user_id])
      puts @user.name
      puts params
      # @micropost = @user.microposts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for( [user, micropost] ) do |f| %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Microposts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr class="row">
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_user_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', user: @user , micropost: @micropost  %>

<%= link_to 'Back', user_microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>